name: wknn
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.8
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - gmp=6.1.2
  - idna=2.9
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.2
  - jupyter_core=4.6.3
  - jupyterlab=1.2.6
  - jupyterlab_server=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1f
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - pyzmq=18.1.1
  - readline=8.0
  - requests=2.23.0
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.8
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - pip:
    - cycler==0.10.0
    - joblib==0.14.1
    - kiwisolver==1.2.0
    - matplotlib==3.1.0
    - pandas==0.24.2
    - pyparsing==2.4.7
    - pytz==2019.3
    - scikit-learn==0.22.2
    - seaborn==0.9.0
    - tqdm==4.45.0
prefix: /home/neilxu/vol0/usr/miniconda3/envs/wknn

